### ISSUE TITLE
Hostname Not Verified please revert to 2.2.6 where IP Address can be used for Self Hosted Docker 

### ISSUE THREAD

**Issue by bachmannn** [bitwarden/mobile#1054]
## Steps To Reproduce

1. Install certificate.crt file from self-signed docker installation
2. Change server settings to your self hosted docker like ``https://192.168.0.123:5555``
3. Try to login

## Expected Result

Be able to connect to Bitwarden self hosted instance and use it normally, just as it is possible on the desktop.

## Actual Result

**An error has occurred. EXCEPTION MESSAGE: Hostname: 192.168.0.123 not verified: Certificate sha1/<<shasum>> DN: CN=192.168.0.123, OU=Bitwarden, O=Bitwarden Inc., I=Santa Barbara ST=California, C=US, SubjectAltNames: 192.168.0.123**

## Environment

- Device: Samsung Galaxy Note 10
- Operating system: Android 10
- Build Version: 2.3.0
- Is this a Beta release? [Y/N] N

## Additional Context

Version 2.2.6 worked fine but the latest updates throw an error message saying that you cannot connect to Docker Self Hosted Bitwarden because hostname is not verified but the IP address is self signed. 

It is not always possible to setup DNS relay just for this one thing.

**Comment by jdubz666** [comment]
+1 

I think I'm experiencing the same issue

**Comment by jkellogg90** [comment]
I had this issue on my Samsung S9 and S3 tablet. What fixed it for me was generating the certificate with a SAN attribute. If using ADCS, this was useful to me.

http://terenceluk.blogspot.com/2017/09/adding-san-subject-alternative-name.html

**Comment by DrIntensive** [comment]
First of all sorry about my English. I think I found the solution (in my case).
I deployed 2 containers: Bitwarden without certificate and Bitwarden with certificate. You only have to call them different, also different ports. For example "Bitwarden" at 70:80 and "Bitwardenwoc" at 71:80, using the first as certified one. But the same port of destiny.
In that cases use the certified one for browsers and the other for the app.
Note: Browser's extensions works with both of them.
- docker run -d --name bitwarden -v /bw-data/:/data/ -p 71:80 bitwardenrs/server:latest
- docker run -d --name bitwardencert --restart unless-stopped -v /bw-data/:/data/ -v /etc/ssl/certs:/ssl -e ROCKET_TLS='{certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}' -p 70:80 bitwardenrs/server:latest

I hope this is helpfully

**Comment by atpanos** [comment]
@bachmannn any news ? here still not working with latest release.

**Comment by DrIntensive** [comment]
As I said, in my method is still working

**Comment by djsmith85** [comment]
@bachmannn and @jdubz666 Are you still experiencing this issue?

I'm closing this now, due to the other reports but can easily be re-opened if you are still experiencing issues.
