### ISSUE TITLE
No items in auto fill

### ISSUE THREAD

**Issue by kevquirk** [bitwarden/mobile#1161]
When adding a new item to my vault, said item doesn't then show on my iOS auto fill.

For example:
- I go to example.com on my iPad and sign up for an account.
- I save my new login details for example.com in the bitwarden app on my iPad.
- I later visit example.com on the same iPad, click passwords and unlock bitwarden to use the auto fill.
- Bitwarden says there are no passwords for this site. So I search for the item, but there are still no results.
- Still on the same iPad, I open the bitwarden app and there is the entry for example.com and I can copy the password.

Syncing doesn't fix the issue. It's repeatable (I've tested on multiple sites and on both my iPhone and iPad), as well as on Safari and Firefox.

This potential bug is killing me. Is this a new one, or user error? I've been using BW for a few years now and this issue had only been happening the last month or so.

Thanks.

**Comment by SergeantConfused** [comment]
Hi there,

This was addressed in the latest version of Bitwarden.
Can you please uninstall Bitwarden off one of your devices, turn it off and back on, and reinstall it?
Please let me know how this goes.

Thank you in advance for your cooperation and understanding.


All the best,

**Comment by kevquirk** [comment]
Hi @SergeantConfused thanks for coming back to me. I didn't need to uninstall, I just opened the App Store and clicked update. Confirmed things are now working how they usually do, thanks.

Question: does the bitwarden app not update itself then?

**Comment by kevquirk** [comment]
This is still happening on my iPhone. I've checked and there is no update available.

**Comment by SergeantConfused** [comment]
Hi there,

The Bitwarden application should be updated by the App Store.

Please uninstall Bitwarden off your device, turn it off, turn it back on, and reinstall Bitwarden.
Let me know if you encounter that on a fresh installation.


Thank you in advance,

**Comment by gwd0715** [comment]
Same issue on my iPhone.
iOS 14.2
Bitwarden 2.7.0

**Comment by mportune-bw** [comment]
Fixed in #1112 and #1182, will be in next release
