### ISSUE TITLE
Bitwarden unable to fulfill password in app

### ISSUE THREAD

**Issue by jyavenard** [bitwarden/mobile#147]
I have an app (Android 7.1) called "Bourse Direct"
https://play.google.com/store/apps/details?id=com.mstv.bd.prod

Bitwarden shows the entry in the notification bar about filling up the entry, but is enabled to find anything for this app, it appears to be looking for com.mstv.bd.prod
The entry on my vault is for boursedirect.com

LastPass has no trouble filling the app, with exactly the same data at hand.
I'm guessing bitwarden only look based on data found in the app Id. While LastPass also look into the name of the app.

Would be good for bitwarden to do the same.

**Comment by kspearrin** [comment]
Is there a way to gain access to the apps full name from the context of the accessibility service? I'll have to look more.

**Comment by jyavenard** [comment]
I have no idea if thats what LastPass is doing.

A suitable alternative would be to let someone choose the related entry and store the relationship for next time.
sometimes, LastPass has such prompt.

**Comment by Abeilard14** [comment]
LastPass is crowdsourcing app associations from its users since a few years, that's why their autofill is working well in apps other than browsers.
Android O autofill will allow developers to provide the necessary info to apps like Bitwarden but It will take a long time to be implemented

**Comment by kspearrin** [comment]
@Abeilard14 I figured. We have plans to crowdsource this as well via GitHub PRs but the solution hasn't been designed yet.

**Comment by jyavenard** [comment]
On those app, I can still perform a manual search and select the entry to use to fill the username/password.

Surely, it could record the link between the app and the entry used so that next time theres no need to manually search for the entry again.

**Comment by auctionsjeff** [comment]
I think this is fixed, since there is an option called "Yes, Add" when selecting an unrelated login.

**Comment by eliykat** [comment]
This issue seems resolved, but I'll also include the following information in case anyone is still experiencing issues.

---

Thanks for reporting this issue. Autofill problems can affect different sites, apps, or devices, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1389. Please also direct any discussion or questions to that issue. This issue will now be closed.
