### ISSUE TITLE
Android error using self-hosted

### ISSUE THREAD

**Issue by JTechHPS** [bitwarden/mobile#209]
I have self hosted setup and working in web browsers. In the Android app, I've entered my server address in  the settings, but get the error: "An error has occurred. There is a problem connecting to the server." I am able to log in through my mobile browser.

**Comment by kspearrin** [comment]
Are you using a self signed cert?

**Comment by JTechHPS** [comment]
Yes, the one generated during setup.

**Comment by kspearrin** [comment]
You need to install it to the trusted store on the android device.

**Comment by JTechHPS** [comment]
I exported the cert from the PC browser and installed it in my mobile trusted store. It is listed, but I get the same error.

**Comment by paescuj** [comment]
Same here. I'm using a self signed cert which I've added to the trust store. It used to work, but stopped with one of the recent updates.

**Comment by paescuj** [comment]
Seems to have been resolved in the latest release [v1.14.0](https://github.com/bitwarden/mobile/releases/tag/v1.14.0)

**Comment by kspearrin** [comment]
Nothing was changed regarding this issue so I am not sure why 🤷‍♂️ 

@JTechHPS can you confirm as well?

**Comment by Shadow00Caster** [comment]
I am having this issue, I previously was using a LE cert, I have switched to a Comodo cert and the issue still persists.  Presumably eliminating the cert as a potential issue, I am using a non-standard port.

**Comment by kspearrin** [comment]
Please check your domain's cert using https://www.digicert.com/help/

**Comment by Shadow00Caster** [comment]
Finally figured this out.  I tested with BW on a the standard 443 and a non-standard port, all with the same result.  What I figured out was that the cert was appearing as not trusted, however I tested with another CA and have various other services using LE certs without issue that show as trusted on multiple SSL testing platforms.

I got this to work by editing the default.conf file in BW's nginx config under `bwdata/nginx/default.conf` and changing the `ssl_certificate` line from the certificate only file provided by LE to the fullchain cert file which is the cert and the CA chain bundle file.  This resolved the issue.

Not sure if this was something that was done from my early attempts at configuration, but I imagine by default the SSL file should be using the fullchain/bundle cert file over the cert only file.

**Comment by kspearrin** [comment]
The default for LE is to reference `fullchain.pem` from the nginx config so it sounds like you changed something.

**Comment by drizuid** [comment]
I am having the same issue. The web plugins work fine, the android app does not. I use let's encrypt certs and can access my site (securely) from external locations. I did not use the let's encrypt container, i manually linked my existing certs. I checked my cert on the link you gave above and got this:   

> SSL Certificate is not trusted
> The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.

even though it shows Issuer | Let's Encrypt Authority X3.

Strangely enough, if I browse to the site using chrome on one of my client's PC's it shows up as trusted with no warnings.

----------------
I see above that you state the default certificate.crt should point to fullchain.pem; this wasn't clearly outlined in the self-hosted guide, so I had used privkey.pem > private.key; fullchain.pem > ca.crt; and cert.pem > certificate.crt.   I've replaced the certificate.crt with the fullchain.pem, but digicert.com still reports that the LE CA isn't trusted in the mozilla root store.

**Comment by markusm** [comment]
I have just installed and got bitwarden to run self hosted.
Accessing it through a browser or browser extensions works fine, but accessing it through the android app does not.
I installed using self-signed certificate.
I also downloaded the certificate from the browser, and installed it on the phone.
Any ideas?

**Comment by ArthurAttout** [comment]
Has this been looked at since then ? I keep on receiving the error on Android aswell, even after installing the certificate on the device.

**Comment by dst78** [comment]
I can confirm that the workaround as described by Shadow00Caster does indeed work for self-signed certificates.
