### ISSUE TITLE
Screen Flashing on Back Navigation since 2023.7.1

### ISSUE THREAD

**Issue by quexten** [bitwarden/mobile#2731]
### Steps To Reproduce

1. Go to "My vault"
2. Click on a Login
3. Navigate back

### Expected Result

The screen should not flash on back navigation.

### Actual Result

The screen flashes.

### Screenshots or Videos

[Screencast from 2023-08-29 11-56-50.webm](https://github.com/bitwarden/mobile/assets/11866552/54ecdd48-af80-47a4-8c67-2c5f59daf442)

### Additional Context

I triaged it down to the PR https://github.com/bitwarden/mobile/pull/2604. As a side-effect of the PR, or more specifically, this part: https://github.com/bitwarden/mobile/blob/e9bfeb2a9e8463ebd1544386acdd0ffd4c20bd7c/src/App/Pages/Vault/GroupingsPage/GroupingsPageViewModel.cs#L387-L392
the screen begins to flash on back navigation. Removing the `Device.BeginInvokeOnMainThread` fixes the bug, but also defeats the point of the PR.

### Operating System

Android

### Operating System Version

Android 13

### Device

Google Emulator, Mi9T Pro

### Build Version

2023.7.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by quexten** [comment]
@Krychaz do note that while I was technically not using a pre-release version, the latest google-play release is still on 2023.07 *which does not have the bug*. On 2023.7.1 and 2023.8.0 I was able to reproduce the bug consistently on 2 different Android phones and the Android emulator. It seems the "flashing" (i.e the list briefly disappearing) is shorter on faster devices (but never completely gone).

Hope that helps to reproduce it.

**Comment by quexten** [comment]
Just tested on iOS on an iPad Pro 2020. On 2023.7.0 the bug does not happen. On the current version from the app store - 2023.8.0 it does happen, although it is much less noticeable. On an older android phone the "flashing" takes around a second, on the ipad it was barely visible:

https://github.com/bitwarden/mobile/assets/11866552/176d30a3-539a-4c76-b072-abceeb79e441

**Comment by vinnyperella** [comment]
This happens every time I open the app from the PIN unlock screen. It started occurring after the version 2023.8.0 update I was hoping it would be fixed with 2023.9.0 but I'm on 2023.9.1 and it is still an issue.

**Comment by sarvesheb** [comment]
Issue still exists on v2023.12.0

**Comment by vinnyperella** [comment]
I believe this is now fixed I'm on version 2024.2.1 and I'm not seeing it anymore.

**Comment by quexten** [comment]
Still happening on iOS, even if less noticeable due to being faster on the device. However, given the native re-write of the apps, I also don't believe this is worth further investigating.

**Comment by quexten** [comment]
Closing. The native apps make this irrelevant.
