### ISSUE TITLE
Vault timeout option not respected on iOS

### ISSUE THREAD

**Issue by ryanpcmcquen** [bitwarden/mobile#2787]
### Steps To Reproduce

- Set "Vault timeout" to "Never".
- Quit Bitwarden from the App Switcher.
- Visit site and log in.
- Get prompted for master password.

### Expected Result

Bitwarden would respect the Vault Timeout setting.

### Actual Result

Bitwarden ignores Vault Timeout and prompts for master password for all interactions.

### Operating System

iOS

### Operating System Version

16.6.1

### Device

iPhone SE 2020

### Build Version

2023.9.1

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Gerardv514** [comment]
Have this issue since 2023.9 update was released. Unfortunately I don’t have a way to roll back since their beta testing group is closed

**Comment by quagsirus** [comment]
Having the same issue on iOS 17.0.1 on my iPhone 11 Pro Max
The vault always locks on app restart regardless of vault timeout or faceid settings.

**Comment by SergeantConfused** [comment]
Hello @ryanpcmcquen and everyone else,

Thank you for your report. I am able to reproduce this on iOS 17 with Bitwarden 2023.9.1, and I have flagged it to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,

**Comment by Gerardv514** [comment]
Thank you for response. Any chance of a way that we can roll back some how? I have a 20 character password which is random generated, this is nearly impossible to deal with on a routine basis.

**Comment by SergeantConfused** [comment]
@Gerardv514,

_Thank you for response._

You're most welcome! 😊

_Any chance of a way that we can roll back some how? I have a 20 character password which is random generated, this is nearly impossible to deal with on a routine basis._

Rolling back on iOS is not a practical option; I would recommend you set up a PIN (https://bitwarden.com/help/unlock-with-pin/) or Biometrics (https://bitwarden.com/help/biometrics/) for now if possible, as a temporary workaround.


All the best,

**Comment by Gerardv514** [comment]
Ah Yes I can set biometric Face ID in mean time. I’m also hit with another bug of kdf memory error when not using biometric. I know a new thread should be created, but I’m not well rehearsed in the argon2 stuff hoping to see someone else post about it. 

Thank you tho for biometric option

**Comment by SergeantConfused** [comment]
@Gerardv514,

Sure thing. Please check if this (https://github.com/bitwarden/mobile/issues/2389) is what you are encountering; If not, please feel free to create a Support ticket (https://bitwarden.com/help/) with more details, and we'll have a look.


All the best,

**Comment by colleenmason** [comment]
I sent a support request about this issue and was sent to this thread. 

>  I would recommend you set up a PIN (https://bitwarden.com/help/unlock-with-pin/) or Biometrics (https://bitwarden.com/help/biometrics/) for now if possible, as a temporary workaround.
> 

FYI Setting up a PIN has not worked for me, I still get asked for master password.

**Comment by ryanpcmcquen** [comment]
> I sent a support request about this issue and was sent to this thread.
> 
> > I would recommend you set up a PIN (https://bitwarden.com/help/unlock-with-pin/) or Biometrics (https://bitwarden.com/help/biometrics/) for now if possible, as a temporary workaround.
> 
> FYI Setting up a PIN has not worked for me, I still get asked for master password.

I have this issue as well.

**Comment by Gerardv514** [comment]
> I sent a support request about this issue and was sent to this thread.
> 
> > I would recommend you set up a PIN (https://bitwarden.com/help/unlock-with-pin/) or Biometrics (https://bitwarden.com/help/biometrics/) for now if possible, as a temporary workaround.
> 
> FYI Setting up a PIN has not worked for me, I still get asked for master password.

Agreed I tried pin too and that doesn’t work. For now I’m utilizing Face ID

**Comment by Gerardv514** [comment]
@SergeantConfused has someone been able to reproduce this yet? Is there a need for further information?

**Comment by thefutureofwhat** [comment]
I have the same issue with my Android 13 device, it appears to be a clear regression in the 2023.9.1 version of the app, started disregarding my settings (to stay unlocked) and (re)locking the vault/app after some small amount of time.

**Comment by xavirg** [comment]
Same here.

Setting the PIN does not solve it, still asking for the master pwd on every login autofill.

**Comment by MinghaoUpUpUp** [comment]
Same here. IOS 17.0.2, 2023.9.1.

**Comment by keldey** [comment]
I followed this guide to downgrade iOS app to `2023.8.0` where the issue was not present:
[https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy](https://github.com/qnblackcat/How-to-Downgrade-apps-on-AppStore-with-iTunes-and-Charles-Proxy)
Using build ID `859421181`.
Hope the fix for this issue could be released soon.

**Comment by feux-follets** [comment]
Same issue here

**Comment by dickaux** [comment]
When might I / we expect a fix?  This issue has been distressing BW users for way to long. Many weeks.

**Comment by muhasturk** [comment]
I dont want to switch over 1Password however this issue is not acceptable.

**Comment by ahsodex** [comment]
> When might I / we expect a fix? This issue has been distressing BW users for way to long. Many weeks.

You think a few weeks is bad, try more than a year as in issue #2371.
I think BW staff largely ignore GitHub. It might be better to open a support issue on their website. I pay for BW so I might try that route myself. 



> I dont want to switch over 1Password however this issue is not acceptable.

I tried 1Password earlier this year for a few months and it didn’t even offer an option to not lock the vault after a timeout period, and also prompted every time for pin/biometric when doing autofill.

**Comment by madmatt347** [comment]
> I think BW staff largely ignore GitHub. It might be better to open a support issue on their website. I pay for BW so I might try that route myself.

Well I put in a ticket a week ago and they just sent me a link to here saying they were already aware of the issue and working on it...

**Comment by SergeantConfused** [comment]
Hello everyone,

Yes, we are able to reproduce this behaviour and are looking into it internally.

As a side note, I've tested using a PIN on iOS 17.0.2 with Bitwarden 2023.9.1, and I am able to unlock my client using that PIN through the Auto-Fill flow. If you are doing this and it's not working, please make sure you tap on (No) when you are asked if you want to require unlocking with your master password when the application is restarted, when you set the PIN up. More about this here (https://bitwarden.com/help/unlock-with-pin/#tab-mobile-DeLAPOlNpLH3MaKazVTfU). If you still are unable to unlock your iOS client using a PIN, please feel free to create a Support ticket (https://bitwarden.com/help/) so we'd have a look because it's probably unrelated to this particular GitHub report.

I thank you in advance for your understanding and patience,

**Comment by muhasturk** [comment]
> > When might I / we expect a fix? This issue has been distressing BW users for way to long. Many weeks.
> 
> 
> 
> You think a few weeks is bad, try more than a year as in issue https://github.com/bitwarden/clients/issues/2371
> 
> 
> 
> I think BW staff largely ignore GitHub. It might be better to open a support issue on their website. I pay for BW so I might try that route myself. 
> 
> 
> 
> 
> 
> 
> 
> > I dont want to switch over 1Password however this issue is not acceptable.
> 
> 
> 
> I tried 1Password earlier this year for a few months and it didn’t even offer an option to not lock the vault after a timeout period, and also prompted every time for pin/biometric when doing autofill. 

There are plenty of security options in 1Password you should check it out again

![image](https://github.com/bitwarden/mobile/assets/4077401/9ebdf43b-c32d-4ecd-a6a5-095790bc8fed)

**Comment by yoshiotobe** [comment]
This also affects Bitwarden 2023.9.1 on Android 11.
I hope the problem will be fixed soon.

**Comment by Retold3202** [comment]
Also impacted by the same issue here on Android 13 (GrapheneOS) ever since updating to 2023.9.1. Hopefully there's a fix soon!

**Comment by Slash8915** [comment]
This issue also persists on Android

**Comment by MeteorsLiu** [comment]
To everyone who has this issue,

downgrade to 2023.8 and don't upgrade.

Android downgrade is easy, maybe there's some difficulty for iOS.

**Comment by trmartin4** [comment]
Hello.  Thank you all for your patience with this very inconvenient behavior as we have been working on a fix.  The resolution to this issue is in development and is currently scoped to be included in the next major release.  We absolutely understand the urgency and sincerely appreciate your patience.

**Comment by andreacpowers** [comment]
When is the next major release?

**Comment by trmartin4** [comment]
@andreacpowers we plan a release in October, but I don't want to commit to an exact date at this point as there are a lot of factors that go in to the exact date.

**Comment by swderek** [comment]
Bug is still present on latest release (2023.9.2 from 11-Oct). I'm on iOS 17.0.3.

**Comment by MinghaoUpUpUp** [comment]
2023.9.2. Still same problem

**Comment by dickaux** [comment]
2023.9.2 didn’t fix the problem. The problem still exists just as in
3023.9.1

**Comment by Gerardv514** [comment]
The bug still exists because the work to fix it hasn’t been started or merged yet.

**Comment by dickaux** [comment]
So What Bugs did 2023.9.2 actually try to fix?

**Comment by 0xadada** [comment]
@dickaux 
> So What Bugs did 2023.9.2 actually try to fix?
you can review the diff here https://github.com/bitwarden/mobile/compare/v2023.9.1...v2023.9.2

**Comment by trmartin4** [comment]
This issue will be included in the next major release (`2023.10.0`), which is currently undergoing final development in preparation for release later this month.

**Comment by escape0707** [comment]
I don't know if those who are pushing the development are actually paid customers, but as far as I'm aware, this is already a speedy fix, and open source software users are usually willing to wait more patiently, because pushing here won't speed up bug fixing as long as devs have already confirmed that they are working on it. Plus, there are more people subscribing to multiple GitHub issues and only want email notifications when something actually changes...

**Comment by escape0707** [comment]
@CarlosJoseChaconChavarria
If you've installed any APK files manually, then you can just go to this repo's release page to grab the history version you need: https://github.com/bitwarden/mobile/releases/tag/v2023.8.0
As for how to enable manual APK installation, there are many guides floating on the internet...

**Comment by justindbaur** [comment]
@wnelson03 An update was already provided, the fix for this issue will be a part of the `2023.10` release.

**Comment by breakthestatic** [comment]
Not 100% sure, but I Believe this PR is what fixes the issue - https://github.com/bitwarden/mobile/pull/2802. As noted above, this was already merged. It like like new builds are normally or out towards the end of the month (seems like there last 2-3 days of the month - going by the past several releases).

**Comment by vrexx1** [comment]
Still an issue (2023.9.2 on Android). Received email from BitWarden 10/24 that asked to close ticket: "It's been a few days since we last assisted you, we hope your request was resolved to your satisfaction.  If you still need help, please reply to this email and we will be glad to continue assisting you. If you no longer need anything for now, there is no need to respond to this message."

**Comment by andreacpowers** [comment]
Yes, Still an issue (2023.9.2 on Android). I cleared cache and still doesn't work. Lastpass was attacked. 1Password was attacked recently and Bitwarden is terrible. I don't know what to do at this point. Please tell them it's not resolved. I wonder if they even tested.

**Comment by escape0707** [comment]
@vrexx1 @andreacpowers 
Please, people, read. And stop spamming my mailbox.

> This issue will be included in the next major release (`2023.10.0`), which is currently undergoing final development in preparation for release later this month.  I apologize for the confusion with the `2023.9.2` release - `2023.9.2` was a small, targeted incremental one, and this fix will be included in our planned October release

**Comment by vrexx1** [comment]
@escape0707  Re: "spam" you'll need to take that up with support@bitwarden.com.

**Comment by MeteorsLiu** [comment]
> @vrexx1 @andreacpowers Please, people, read. And stop spamming my mailbox.
> 
> > This issue will be included in the next major release (`2023.10.0`), which is currently undergoing final development in preparation for release later this month.  I apologize for the confusion with the `2023.9.2` release - `2023.9.2` was a small, targeted incremental one, and this fix will be included in our planned October release

You can click the button "Unsubscribe" below, the GitHub will not notice you again. I think the reason why this issue is hot is that people really need the "never timeout" option. Bitwarden is my password manager, i cannot stand that i have to input my another password again every time i want to fill my password via bitwarden. That's really silly and really a problem.

So why people are pushing the developers, read my words.

**Comment by jidanni** [comment]
Just curious as what happens/happened to passwords of new accounts (on websites we browsed)  created while this bug is/was present? Not remembered and lost forever?

**Comment by Voykimmer** [comment]
Well a fix was supposed to be out the end of October with 2023.10 .  Well today is the end of October and still no fix. What gives ?  Am I going to have to move to another password manager again ?

**Comment by 0xadada** [comment]
@Voykimmer 

> Well a fix was supposed to be out the end of October with 2023.10 . Well today is the end of October and still no fix. What gives ? Am I going to have to move to another password manager again ?

@wnelson03 

> just don't understand why wait & put such a prevalent bug fix in a major release.

The release process is more than just merging a fix PR and running a build. There are multiple engineering teams involved, multiple platforms (Safari/Chrome/Firefox x iOS/Windows x Desktop/Mobile, etc), and multiple AppStores (Google Play, AppStore, etc), marketing, coms, etc that all need to be coordinated.

**Comment by escape0707** [comment]
> I just don't understand why wait & put such a prevalent bug fix in a major release.

Because usually when developers fix a bug, they will first implement the fix at the current developing branch. That fix usually can't be simply copy paste to older releases because there are code differences between them. Only when an issue is serious enough or the developing force is just too rich will it be back-ported to a previous release. This effectively doubles the test time needed.

Just for reference, [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1859945) is a even more annoying Firefox bug currently in Firefox 119 release, but Mozilla didn't choose to back-port the fix to 119, either.

**Comment by escape0707** [comment]
The annoyance of the white flash even with dark reader and dark theme is described in this thread https://github.com/darkreader/darkreader/issues/11190#issuecomment-1737877948

**Comment by muhasturk** [comment]
2023.10.0 release hasn't fixed. this issue when using auto fill feature, it asks to enter master password every time.
iOS 16.7.2

**Comment by andreacpowers** [comment]
Not updated for Android yet. 
Reminder to check each place you have Bitwarden: extensions on each browser, app on phone.

**Comment by sinamics** [comment]
when will the android version be out?

**Comment by Voykimmer** [comment]
my iPad and iPhone still at 
Version: 2023.9.2 (5102) and no update available yet and Bitwarden is still broken.

**Comment by Voykimmer** [comment]
I’m at IOS 16.7.2 on both my iPhone 8 and my 
iPad (6th generation) and no update has been pushed to either yet .

**Comment by linicholas19** [comment]
I am on version 2023.10.0 and it is still asking me for Face ID every time. I’ve set the timeout to never but the issue still occurs.

**Comment by muhasturk** [comment]
[video proof](https://youtube.com/shorts/BvJSo__2rBY?si=9VPpX2In785DQlSR)

**Comment by Gerardv514** [comment]
> [video proof](https://youtube.com/shorts/BvJSo__2rBY?si=9VPpX2In785DQlSR)

Can you turn off the option “ unlock with Face ID” and keep vault time out set to never again.

**Comment by madmatt347** [comment]
Update to 2023.10.0 fixed the issue for me on Android 5.1

Thanks Devs

**Comment by Voykimmer** [comment]
I deleted the Bitwarden app and downloaded and reinstalled from the App Store and I got 2023-10 and now everything works great. You do have to go in the settings and change timeout to never again tho.

**Comment by jidanni** [comment]
![Screenshot_20231106_092141_Google Play Store.jpg](https://github.com/bitwarden/mobile/assets/1230959/967a6f1f-5897-4624-a73f-6577a4a7780b)

No update if you are an Android beta tester.

**Comment by Swap-File** [comment]
Fixed as of yesterday on Android.

**Comment by LPFchan** [comment]
This issue has been bugging me for quite a while now, happy to report both opening the app AND autofill behaviour returned to normal. but I had to disable 'Unlock with Face ID' in order for vault timeout option to be respected. Perhaps the toggle should be disabled when the timeout is set to 'Never'?

**Comment by cdonovan** [comment]
This is still occurring for me with 2023.10.0 on Android. I completely uninstalled the app to be sure there were no old configurations messing it up. The frequency of needing to unlock has decreased but I still see it at least once a day. Should I report this as a new bug or continue investigating/providing logs here?

**Comment by escape0707** [comment]
> This is still occurring for me with 2023.10.0 on Android. I completely uninstalled the app to be sure there were no old configurations messing it up. The frequency of needing to unlock has decreased but I still see it at least once a day. Should I report this as a new bug or continue investigating/providing logs here? 

Turn off biometric unlock and try again.

**Comment by cdonovan** [comment]
> > This is still occurring for me with 2023.10.0 on Android. I completely uninstalled the app to be sure there were no old configurations messing it up. The frequency of needing to unlock has decreased but I still see it at least once a day. Should I report this as a new bug or continue investigating/providing logs here?
> 
> Turn off biometric unlock and try again.

Thanks for tip! I guess that follows the same mechanism as the noted Face ID comment above mine. Just disabled the biometric unlock - will see how it goes 🤞.
