### ISSUE TITLE
App crashing when trying to add new password

### ISSUE THREAD

**Issue by kubab6** [bitwarden/mobile#2838]
### Steps To Reproduce

1. Click + Button to add new Password to Vault
2. Enter name, username and password
3. Click Save

### Expected Result

Password gets added to Vault

### Actual Result

App crashes and password doesn‘t get added to Vault

### Additional Context

Selfhosted Instance (Working on Web Vault and Desktop though)

### Operating System

iOS

### Operating System Version

iOS 17.1

### Device

iPhone 12 mini

### Build Version

2023.9.2 (5102)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by JaKooB89** [comment]
I'm experiencing exactly the same issue but on Pixel 6 Pro / Android 14

**Comment by fxzxmicah** [comment]
I have the same problem when I generate a new password for an existing account.
Android 13.

**Comment by imc67** [comment]
Same here! Very very annoying

**Comment by dany85free** [comment]
It also doesn't allow me to modify or add new items auto-detected by Android

**Comment by imc67** [comment]
> Same here! Very very annoying

For me it's solved now. I use Cloudron as platform and Vaultwarden as app. Today the Cloudron team updated the app and now it's solved: https://forum.cloudron.io/topic/10303/using-bitwarden-android-app-crashs-when-i-save-any-edits

**Comment by He-Ro** [comment]
Here is a crash report. It came up when pressing "save" on a new entry creation:

```
type: crash
osVersion: xxx
package: com.x8bit.bitwarden:8257
process: com.x8bit.bitwarden
processUptime: 52299428 + 340 ms
installer: com.android.packageinstaller

android.runtime.JavaProxyThrowable: System.ArgumentNullException: Value cannot be null.
Parameter name: version
  at Bit.Core.Utilities.VersionHelpers.RemoveSuffix (System.String version) [0x0000c] in <936ae15b13fb4cde85a914994b1b1639>:0 
  at Bit.Core.Utilities.VersionHelpers.IsServerVersionGreaterThanOrEqualTo (System.String targetVersion, System.String compareToVersion) [0x00001] in <936ae15b13fb4cde85a914994b1b1639>:0 
  at Bit.Core.Services.CipherService.ShouldUseCipherKeyEncryptionAsync () [0x000a5] in <936ae15b13fb4cde85a914994b1b1639>:0 
  at Bit.Core.Services.CipherService.UpdateCipherAndGetCipherKeyAsync (Bit.Core.Models.Domain.Cipher cipher, Bit.Core.Models.View.CipherView cipherView, Bit.Core.Models.Domain.SymmetricCryptoKey key, System.Boolean shouldCreateNewCipherKeyIfNeeded) [0x00154] in <936ae15b13fb4cde85a914994b1b1639>:0 
  at Bit.Core.Services.CipherService.EncryptAsync (Bit.Core.Models.View.CipherView model, Bit.Core.Models.Domain.SymmetricCryptoKey key, Bit.Core.Models.Domain.Cipher originalCipher) [0x0062a] in <936ae15b13fb4cde85a914994b1b1639>:0 
  at Bit.App.Pages.CipherAddEditPageViewModel.SubmitAsync () [0x00636] in <5d9edd388158496783b4c62056558d1c>:0 
  at Bit.App.Pages.CipherAddEditPage.Save_Clicked (System.Object sender, System.EventArgs e) [0x00084] in <5d9edd388158496783b4c62056558d1c>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <21c3e99f3bf94f1fb39e4af2d240aad5>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <2709d3f558e74d94b1e89fc943d252af>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2709d3f558e74d94b1e89fc943d252af>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <2709d3f558e74d94b1e89fc943d252af>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <2709d3f558e74d94b1e89fc943d252af>:0 
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

**Comment by Tlepel** [comment]
@He-Ro for me the new vaultwarden server release didn't fix the issue at all; are you sure it's fixed?

------

My (self-hosted) server doesn't receive a request when trying to save new credentials through the app, which to me seems to indicate a bug that is independent of the server, unless the server configuration that's loaded in the app causes some trouble. I'm not familiar with how the app works exactly, but the reproduction steps still seem to be triggering the error with me.

I could try to see what the crash log looks like, but I'd have to know how to get to them (so if anyone could help out with that, that'd be great!)

**Comment by He-Ro** [comment]
Yes, for me the Vaultwarden update was enough to fix the problem. I can use the steps within the issue description to create a new entry within the application. But note that I used the Android application in the following version: 2023.10.0 (8257)

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Based on this, as well as helpful comments on this issue from other users, I believe the behavior may be related to Vaultwarden. Vaultwarden is a separate project that is not maintained by Bitwarden. For Vaultwarden support, please visit their site: https://vaultwarden.discourse.group/c/help/7

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
