### ISSUE TITLE
Please add Firefox Nightly to fido2_privileged_allow_list.json.

### ISSUE THREAD

**Issue by h4WXNlvFF1e4H0qUae7jvuhmzg8hB19p3no4JhB** [bitwarden/mobile#3315]
### Steps To Reproduce

1. Navigate to a website that supports passkey.
2. The passkey list is shown.
3. Select a passkey.

### Expected Result

Bitwarden shows (fingerprint)authentication form and continues to website.

### Actual Result

An error occurred. "Passkey operation failed because browser is not privileged" 

### Additional Context

There is no Firefox nightly(*org.mozilla.fenix*) in `fido2_privileged_allow_list.json`.

### Operating System

Android

### Operating System Version

14

### Device

Samsung Galaxy S24+

### Build Version

2024.5.1 (10574)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by RadNotRed** [comment]
Can Iceraven also be added? Firefox fork for Android https://github.com/fork-maintainers/iceraven-browser

**Comment by yetdragon** [comment]
[Fennec](https://f-droid.org/packages/org.mozilla.fennec_fdroid/) (F-Droid's fork of Firefox) also seems to be not in the list.

**Comment by M3gaFr3ak** [comment]
[Mull](https://f-droid.org/en/packages/us.spotco.fennec_dos/) also isn't privileged.

**Comment by bb010g** [comment]
How are browser developers on Android expected to work around this when testing passkey support with Bitwarden?

**Comment by bb010g** [comment]
This issue was introduced by:
+ https://github.com/bitwarden/mobile/pull/3190

Could we be informed of the reasoning behind PM-7658 and why it's beneficial and/or necessary for Bitwarden to implement its own verification on top of Android's existing passkey flow?

**Comment by KiARC** [comment]
Seconding bb010g: This seems like a poor design choice. What benefit is there to locking out uncommon/nonstandard browsers from passkey usage? Surely it should be the user's responsibility to avoid unsafe browsers, not Bitwarden's to refuse to interoperate with them.

If there really is a need for this, perhaps a setting could be added by which users can whitelist specific apps (such as Firefox Nightly) to be considered privileged, so that at the very least it isn't something that requires a PR to fix for each new browser.

**Comment by hellfire103** [comment]
How's it looking?

**Comment by vvolkgang** [comment]
👋🏾 We're following Google's security guidelines and API requirements, as documented here: https://developer.android.com/identity/sign-in/credential-provider#obtain-allowlist

In the new bitwarden/android repository we recently improved this approach by creating a community supported allow list file where you'll find some of the browsers previously mentioned in this thread and are also free to contribute to with additional browsers: 

https://github.com/bitwarden/android/blob/main/app/src/main/assets/fido2_privileged_community.json

**Comment by Snuupy** [comment]
> 👋🏾 We're following Google's security guidelines and API requirements, as documented here: https://developer.android.com/identity/sign-in/credential-provider#obtain-allowlist
> 
> In the new [bitwarden/android](https://github.com/bitwarden/android) repository we recently improved this approach by creating a community supported allow list file where you'll find some of the browsers previously mentioned in this thread and are also free to contribute to with additional browsers:
> 
> https://github.com/bitwarden/android/blob/main/app/src/main/assets/fido2_privileged_community.json

Hi, this list should not be hardcoded (or there should be a user setting to add browser package names to the list in the app that is passed onto the API.

**Comment by yoyo930021** [comment]
In fact, the Firefox Nightly org.mozilla.fenix mentioned in this issue still hasn’t been added to the allowed list?​

**Comment by lucasmz-dev** [comment]
This should now be fixed in the main branch for the native app, Firefox Nightly should work soon (#3261)

I originally did not add F Nightly because I honestly thought it was already trusted by Google, actually in my mind I had seen it, anyone using Mull, Fennec, Mulch, CalyxOS Chromium, Cromite (possibly a few others I don't remember) those are already in the list and if they're not working, it's either the browser not properly using the right APIs, or you're not in Android 14+, or something else's off with BW. The Chromium browsers seem to be a bit broken with that ATM unfortunately.

**Comment by 50P15** [comment]
According to https://github.com/bitwarden/android/blob/main/app/src/main/assets/fido2_privileged_community.json
Quetta browser is supported, but I still get the same "Passkey operation failed because browser is not privileged".
Is it because that file isn't live yet?
Is there a way to whitelist a browser, even if it requires root?

**Comment by closebot-bw** [comment]
This repo has been archived. To report an issue you're experiencing in the new native apps, visit the [iOS](https://github.com/bitwarden/ios) / [Android](https://github.com/bitwarden/android) repo.
