### ISSUE TITLE
App Security Lock Options doesn't work

### ISSUE THREAD

**Issue by boriskindy** [bitwarden/mobile#49]
I have this feature set to lock the app in 1 minute. However, the app does not lock automatically and I have to manually lock the app.

**Comment by kspearrin** [comment]
Is this on android? Did it used to work? Wondering if this is something that broke in 1.4.0

**Comment by boriskindy** [comment]
Yes, this issue is with Android version 7.0. I've only been using the app
for the past month or so and as far as I know the auto lock feature has not
worked at all.

**Comment by kspearrin** [comment]
I just tested and it worked for me. I think you are misunderstanding how the locking works. It does not lock the app if you still have it open on screen. It only locks the app after being backgrounded for 1 minute. Is this what you are seeing or is locking not working from the background either?

**Comment by boriskindy** [comment]
The app does not lock in the background. Sometimes I forget to lock it and
come back to the app a day later after using other apps in the meantime and
it's still unlocked.

**Comment by kspearrin** [comment]
That's really odd. First I have heard this. What device are you using?

**Comment by boriskindy** [comment]
It's a OnePlus 3T running Android version 7.0 and OxygenOS version 4.0.3.

**Comment by kspearrin** [comment]
I think @Primokorn has that same device. Does it work for you @Primokorn ?

**Comment by Primokorn** [comment]
It does work on my OP3T but I have a custom ROM based on Lineage OS.

**Comment by boriskindy** [comment]
Thanks for that. I might try another ROM.

**Comment by timdvail** [comment]
I experience this problem too. I have a Motorola Pure X phone and android version 6.

**Comment by sreich** [comment]
I can reproduce this as well, Pixel XL (7.1.2).

It sometimes works though, but often will indeed, not lock.

**Comment by sreich** [comment]
Confirmed to be present and sporadic in 1.1.0, so this isn't a regression.

**Comment by kspearrin** [comment]
Thanks all. I have an idea of where the issue is but it is tough since I cannot reproduce it myself. I'll have to try a bland fix and get you guys to validate.

**Comment by magicguitarist** [comment]
My wife just asked me about this same issue, Galaxy S7 with Bitwarden 1.4.4 (517). She installed the app, turned on the option for auto lock 1 in minute and watched about a half an hours worth of videos and checked the app, still unlocked

**Comment by boriskindy** [comment]
I'm not a programmer but there must be another way to engineer the lock
option as the problem doesn't appear to be present in the Keeper or
LastPass apps for android. I do prefer Bitwarden, however, and will put up
with this bug in the hope that one day there will be a fix. Or perhaps I'll
try another ROM on my OnePlus 3T.

**Comment by kspearrin** [comment]
This should be resolved in the next version.

**Comment by kspearrin** [comment]
This is now available in the play store as part of the beta. Can anyone here that was experiencing the issue try it out and see if it is still an issue for them?

https://play.google.com/store/apps/details?id=com.x8bit.bitwarden

**Comment by boriskindy** [comment]
The only version of bitwarden I'm able to see in the play store is version 1.4.4 updated on 11 March 2017. This is the version already installed and the lock issue is still present. Should I be testing a later version?

**Comment by kspearrin** [comment]
It should be 1.4.4 build 549. It is in the beta slot.

**Comment by kspearrin** [comment]
Check settings > about to make sure you are not on 517.

**Comment by boriskindy** [comment]
I'm on build 517 and can't figure out how to install build 549 through the
play store. Google suggest that I should be able to join a beta programme
as follows:

Get beta versions of apps

Beta apps are new, experimental versions of apps that are currently
available on the Play Store. The beta version may have features that are
not available in the public version yet.

To get the beta version of an app you have to have the public version
installed. To check if an app has a beta version available:

Open the Google Play Store.

Find the app you want to check and tap it to go to the app detail page.

Look to see if the app detail page mentions a beta version. Make sure you
scroll down as this information could be at the bottom of the page.

If it’s available, tap Join.

The above doesn't help. Please advise.

Boris

**Comment by kspearrin** [comment]
You do not see a join button on the play store page?

**Comment by boriskindy** [comment]
I found it in the end. On the play store bitwarden page underneath What's
new/Read more/my own rating/the 3 most recent review headers/Similar
apps/Ads related to this app/You might also like/Recommend for you... There
it was... In all it's shining glory, the Become a Beta tester section!

Sorry. I didn't see it until now.
The good news is I've installed version 1.4.4 (550) and the app now locks
after the specified period.

Success!

Thank you.

**Comment by kspearrin** [comment]
Great. This should be released sometime later this week.

**Comment by luetage** [comment]
I started using bitwarden a day ago. I like it so far, but the lock option on Android still seems to have problems. Automatically locking immediately or after 1 minute works as expected, but 15 minutes and 1 hour are dysfunctional. I am on a oneplus x on Android 6. Bitwarden version 1.14.4.

**Comment by kspearrin** [comment]
@luetage What are you observing with 15 min? Does it never lock or what?

**Comment by luetage** [comment]
Hey, I just tried again to make sure. I set to 15 minutes last night and when I checked this morning, the bitwarden app on android was still unlocked and I could access my passwords. Happy for any pointers. Greetings, luetageOn 16 Mar 2018 19:46, Kyle Spearrin <notifications@github.com> wrote:@luetage What are you observing with 15 min? Does it never lock or what?

**Comment by kspearrin** [comment]
Hmm. I just tested 1m 15m, and 1h and all worked fine so I am not sure. Can you open a new issue with info about your device please?

**Comment by flipovic** [comment]
I have the same problem, with the lock configured for 15m, I close the app, wait more than 15m and when I open the app again it is unlocked! But this is happening only some times, earlier today the app correctly asked me to unlock it but now somehow it is not working (tried a couple of times on the last 2 hours) and I can't think of a reason why.

My device info:
- **Phone Model:** Wiko Pulp
- **Android Version:** 5.1
- **Kernel Version:** 3.10.72+
- **Bitwarden Version:** 1.15.2

**Comment by flipovic** [comment]
Just tried to more times, to see If I could find the reason, but now it is working as expected! This is a twilight zone kind of bug... If it happens again I'll open a new issue for it (sorry for posting on a closed one).
