### ISSUE TITLE
Can't connect to self hosted vault with new android app

### ISSUE THREAD

**Issue by ministryofsillywalks** [bitwarden/mobile#538]
I'm running bitwarden server version 2.10.1 inside a docker container.
Today I updated my Android Phone (Pocophone Running Lineage 16) to the new Bitwarden release (2.0.4) but now I can't connect to my vault anymore.
I get the error code:
There is a problem connecting to the server
Accessing the vault via web interface or the windows app still works flawlessly.
I checked my ssl cert as this was an error that other people had but the check comes back with no problems.
I tried both the play store version for android and the f-droid version. The error persists.
Can I somehow provide you logs for a better understanding whats going on?

**Comment by kspearrin** [comment]
Is this server publicly accessible? How are you accessing it? Via IP address or a domain?

**Comment by ministryofsillywalks** [comment]
Via Domain.
Running it on my home server through a reverse proxy (caddy) 
Last app version worked without any issues.

**Comment by kspearrin** [comment]
Can you try dev build 1929 from here and see if it works? https://ci.appveyor.com/project/bitwarden/mobile/build/job/46mal0wu54lsog33/artifacts

**Comment by ministryofsillywalks** [comment]
I'm going to be honest... I don't really know how I would deploy it?
Currently I'm just grabbing the latest version from docker hub and keeping it up to date via watchtower...

**Comment by kspearrin** [comment]
Resolved in v2.0.6 with https://github.com/bitwarden/mobile/commit/8f18c4fd455fd2017c5e8e39a7aa413b6e1f23db

**Comment by ministryofsillywalks** [comment]
still not working for me!
see my answer here:
https://github.com/bitwarden/mobile/commit/8f18c4fd455fd2017c5e8e39a7aa413b6e1f23db#commitcomment-33955834

**Comment by kspearrin** [comment]
Is your server publicly available? Could I try connecting to it from my end to debug it more? You could email me the domain if necessary.

**Comment by ministryofsillywalks** [comment]
@kspearrin
I restarted my home server and now it's working. Seems to have been an issue on my end! Thanks anyhow!
