### ISSUE TITLE
Android 10.0 - There is a problem connecting to the server.

### ISSUE THREAD

**Issue by efsg** [bitwarden/mobile#630]
Unable to login
PlayStore(stable&beta)
"There is a problem connecting to the server."
![avatar](https://upload.cc/i1/2019/10/18/R7gqZk.png)

**Comment by kspearrin** [comment]
Sounds like you have an issue with the Play Store? Can you download other apps?

**Comment by efsg** [comment]
> Sounds like you have an issue with the Play Store? Can you download other apps?

Essential Phone stock
Unable to login(bitwarden)

**Comment by kspearrin** [comment]
Does your device allow internet permissions for the Bitwarden app? Have you tried changing networks to see if that helps?

**Comment by GitSchorsch** [comment]
Same here on two Devices, both with Android 9. I'm running a self hosted Bitwarden Server with a LE certificate. No problems with Chrome or Firefox, only the mobile app on Android cannot connect to the server. After a downgrade to version 2.2.2 everthing is fine, it works like a charm.

**Comment by kspearrin** [comment]
@GitSchorsch Would you mind sharing the endpoint for this self-hosted server so that I can try to connect to it while debugging and see what the error is? You can email me the URL directly here: https://www.kylespearrin.com/

**Comment by mfjt** [comment]
Also not working in my Android 9 one (SONY Xperia XZ1 Compact).
I'm using officially hosted Bitwarden server.

Ver. 2.2.2 was no problem.
But after update to 2.2.6, can't connect server - e.g. synchronize with vault, download web site icons, new login...

**Comment by kspearrin** [comment]
@mfjt can you share your servers endpoint so that I can test it?

**Comment by mfjt** [comment]
@kspearrin I'm not set up endpoint and any other URLs. There are leave blank.

**Comment by kspearrin** [comment]
@mfjt  You are using the Bitwarden Cloud servers?

**Comment by mfjt** [comment]
@kspearrin Probably. Web vault URL is https://vault.bitwarden.com/

**Comment by kspearrin** [comment]
@mfjt Are you using wifi or cellular? Could you try switching networks and see if that changes anything?

**Comment by jonastps2015** [comment]
Hi,
I am facing the same problem as @mfjt and @GitSchorsch.
Also had to downgrade to version 2.2.2 to make it work.
I tried both cellular and wifi without any change.

Environment : Samsung Galaxy S8, Android 9, self-hosted server.

**Comment by kspearrin** [comment]
@jonastps2015 Official self-hosted server or a community-developed one?

**Comment by jonastps2015** [comment]
@kspearrin You do have a point there, I am using bitwarden_rs implementation which I believe is not official.
Since all I did was to update the android client app and don't have any problem with other clients, I did not suspect the server side.
You might be right. I would understand if you do not want to investigate that point.
I am going to check bitwarden_rs issue tracker.

**Comment by mfjt** [comment]
@kspearrin It was able to connect (sync and download icons) server via the cellular network, but can't connected in via Wi-Fi.

**Comment by kspearrin** [comment]
Can you guys try the latest beta version on the play store and see if anything changes?

**Comment by GitSchorsch** [comment]
I'm back to the beta program, but got still the version from 8.11. (which has the problem described above). Can you provide a test-version via download here on GitHub?

**Comment by kspearrin** [comment]
I just released build version 2120 on the play store beta track. It contains some updates that will show a more detailed error message of what the actual error is. Please update and let me know what the error is telling you now (or if the problem is resolved).

**Comment by GitSchorsch** [comment]
The new version is installed, unfortunately the problem is not resolved. The error message is "Exception message: An error occurred while sending the request." Hope this helps. Thanks for your work.

**Comment by mfjt** [comment]
@kspearrin Message was shown "Exception message: mono-io-layer-error (-1)".

**Comment by kspearrin** [comment]
Can you try build number 2125 from the beta track on the play store and see if there is any difference? I just pushed it out.

**Comment by GitSchorsch** [comment]
There is a difference, it works!

**Comment by kspearrin** [comment]
Great! Can anyone else also confirm?

**Comment by mfjt** [comment]
@kspearrin The problem is almost solved! But web-site icons are not displayed.

**Comment by kspearrin** [comment]
@mfjt Can you try a full reinstall and see if that fixes them?

**Comment by mfjt** [comment]
@kspearrin There is no difference after full reinstall...

**Comment by kspearrin** [comment]
Can you try build 2126 to see if the icons are now working? It should be available in beta on the Play Store.

**Comment by GitSchorsch** [comment]
I do not have any problems with icons, not even with version 2125.

**Comment by mfjt** [comment]
@kspearrin Still not working in version 2128

**Comment by kspearrin** [comment]
@mfjt What isn't working? Only the icons?

**Comment by yiyiwangru** [comment]
I also have this problem. Will it be fixed in the next version? @kspearrin

**Comment by mfjt** [comment]
@kspearrin Yes, my device working as below

Network Type | Login | Sync | Add item | Icons
-------------|-------|------|----------|------
Cellular     | OK    | OK   | OK       | OK
Wi-Fi        | OK    | OK   | OK       | NG

**Comment by djsmith85** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

Regarding the second issue with the icons: The client has received several improvements since this report. Please check, if this is still an issue with the latest version and if so, please open a new issue.
